services:

    ssk-auth-app:
        image: ciceroreis/ssk-application:latest
        container_name: ssk-auth-app
        ports:
            - "8001:8080"
        volumes:
            - ./../ssk_auth_app:/application
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - OCTANE_PORT=8080
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - sail
        depends_on:
            - redis
            - localstack

    ssk-auth-app-db:
        image: mysql:5.7.22
        container_name: ssk-auth-app-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ssk_auth_app_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ssk_auth_data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - sail   
    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    localstack:
        image: localstack/localstack
        container_name: ssk_localstack
        ports:
            - "127.0.0.1:4566:4566"
            - "127.0.0.1:4510-4559:4510-4559"
        environment:
            #- DEBUG=${DEBUG:-0}
            - DEBUG=1 # Ativa a depuração
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ssk_localstack:/var/lib/localstack
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - sail
            
networks:
    sail:
        driver: bridge

volumes:
    ssk_auth_data:
        driver: local
    sail-redis:
        driver: local
    ssk_localstack:
        driver: local
